name: compuling-environment
channels:
  - conda-forge
dependencies:
  - beautifulsoup4
  - chardet
  - matplotlib
  - nltk==3.4.5
  - pip
  - rise
  - spacy==3.3.1
  - pip:
    - git+https://github.com/ClaudeCoulombe/FrenchLefffLemmatizer.git
  - script:
    - python -m spacy download fr_core_news_sm
