name: compuling
channels:
  - conda-forge
dependencies:
  - beautifulsoup4
  - chardet
  - matplotlib
  - nltk
  - numpy
  - pip
  - seaborn
  - spacy
  - pip:
    - git+https://github.com/ClaudeCoulombe/FrenchLefffLemmatizer.git
