name: compuling
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4
  - chardet
  - gensim
  - jupyterlab
  - jupyterlab-latex
  - matplotlib
  - nltk
  - numpy
  - pandas
  - pip
  - pillow
  - python=3.10
  - scikit-learn
  - scipy
  - seaborn
  - spacy
  - tabulate=0.9.0
  - wordcloud
  - pip:
    - git+https://github.com/ClaudeCoulombe/FrenchLefffLemmatizer.git
