name: compuling-environment
channels:
  - conda-forge
dependencies:
  - beautifulsoup4
  - chardet
  - matplotlib
  - nltk==3.4.5
  - pip
  - spacy==3.3.0
  - pip:
    - git+https://github.com/ClaudeCoulombe/FrenchLefffLemmatizer.git
