name: compuling
channels:
  - conda-forge
dependencies:
  - beautifulsoup4
  - chardet
  - gensim
  - jupyterlab
  - jupyterlab-latex
  - matplotlib
  - nltk
  - numpy
  - pip
  - python=3.10
  - scikit-learn
  - seaborn
  - spacy
  - wordcloud
  - pip:
    - git+https://github.com/ClaudeCoulombe/FrenchLefffLemmatizer.git
