[project]
name = "Compuling"
version = "0.1.1"
description = "Resources to learn how to manage corpus with Python."
authors = ["Alexandre Roulois <alexandre.roulois@u-paris.fr>"]
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/Alex-bzh/compuling"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[tasks]
start = "jupyter lab"

[dependencies]
beautifulsoup4 = "~=4.12"
chardet = "~=5.1"
gensim = "~=4.3"
jupyterlab = "~=4.1"
jupyterlab-latex = "~=3.0"
matplotlib = "~=3.0"
nltk = "~=3.8"
numpy = ">1.25"
pandas = ">2.0"
pillow = "~=10.2"
pip = ">23.3.0"
python = ">3.10"
scikit-learn = "~=1.4"
scipy = "~=1.12"
seaborn = ">0.13.0"
spacy = "~=3.7"
tabulate = "~=0.9"
wordcloud = "~=1.9"
