#!/bin/bash

#
# spacy
#
python -m spacy download fr_core_news_sm

#
# TreeTagger
#
# go to TT folder
cd ./5.pos-tagging/TreeTagger

# get Linux tagger package
wget https://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/tree-tagger-linux-3.2.4.tar.gz

# get tagging scripts
wget https://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/tagger-scripts.tar.gz

# get parameter files
wget https://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/english.par.gz
wget https://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/french.par.gz

# get installation script
wget https://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/install-tagger.sh

# install
sh install-tagger.sh

export PATH=$PATH:$HOME/5.pos-tagging/TreeTagger/bin
export PATH=$PATH:$HOME/5.pos-tagging/TreeTagger/cmd
